SELECT * FROM customer LIMIT 10;

-- what is the total revenue generated by male and female customer
SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer
GROUP BY gender;

-- which customer used discount still spent more than average purchase amount
CREATE VIEW discount_inquiry AS 
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND
purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

SELECT * FROM discount_inquiry;
SELECT COUNT(*) FROM discount_inquiry;

-- which are the top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating::"numeric"),2) AS "average_product_rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- compare the average purchase amount between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount)) 
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) AS "total_customer", ROUND(AVG(purchase_amount),2) AS "average_spend", ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC;


-- which 5 products have the highest purchases with discount applied
SELECT item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

CREATE VIEW customer_type AS 
SELECT 
    customer_id, 
    previous_purchases,
    CASE 
        WHEN previous_purchases = 1 THEN 'NEW'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
        ELSE 'LOYAL'
    END AS loyal_segment  -- No single quotes here
FROM customer;

SELECT loyal_segment, COUNT(*) AS "customer_typing"
FROM customer_type 
GROUP BY loyal_segment;

